blueprint:
  name: Sunrise Light Simulator (Loop w/ Kevin setting)
  description: Gradually brighten lights and change color to simulate a sunrise over a specified duration using a loop-based approach. Specify by Light entity, Area, or Label.
  domain: automation
  input:
    target_lights:
      name: Lights
      description: Select lights by entity, area, device, or label for the sunrise simulation
      selector:
        target: {}
    start_time:
      name: Start Time
      description: Time to start the sunrise simulation
      selector:
        time: {}
    duration:
      name: Duration (minutes)
      description: How long the sunrise should last (in minutes)
      default: 45
      selector:
        number:
          min: 3
          max: 120
          step: 1
          unit_of_measurement: minutes
    max_brightness:
      name: Maximum Brightness
      description: The maximum brightness level to reach at the end of the sunrise
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
    start_kelvin:
      name: Start Kelvin Temperature
      description: The starting color temperature in Kelvin (warm)
      default: 2000
      selector:
        number:
          min: 2000
          max: 5000
          step: 200
          unit_of_measurement: "K"
    stop_kelvin:
      name: Stop Kelvin Temperature
      description: The ending color temperature in Kelvin (cool). Must be at least 1000K higher than start.
      default: 3000
      selector:
        number:
          min: 2000
          max: 5000
          step: 200
          unit_of_measurement: "K"
    pre_sunrise_actions:
      name: Pre-Sunrise Actions (Optional)
      description: Actions to run before the sunrise simulation starts
      default: []
      selector:
        action: {}
    post_sunrise_actions:
      name: Post-Sunrise Actions (Optional)
      description: Actions to run after the sunrise simulation completes
      default: []
      selector:
        action: {}

trigger:
  - platform: time
    at: !input start_time

condition:
  - condition: template
    value_template: "{{ (stop_kelvin - start_kelvin) >= 1000 }}"
    alias: "Validate: Stop Kelvin must be at least 1000K higher than Start Kelvin"

variables:
  duration: !input duration
  max_brightness: !input max_brightness
  start_kelvin: !input start_kelvin
  stop_kelvin: !input stop_kelvin
  # Convert max_brightness percentage to 0-255 scale
  max_brightness_value: "{{ (max_brightness * 255 / 100) | int }}"
  # Calculate increments per minute
  brightness_increment: "{{ max_brightness_value / duration }}"
  # Kelvin range based on user settings
  kelvin_range: "{{ stop_kelvin - start_kelvin }}"
  kelvin_increment: "{{ kelvin_range / duration }}"

action:
  # Run pre-sunrise actions
  - choose: []
    default: !input pre_sunrise_actions

  # Loop through each minute of the duration (starting from minute 0)
  - repeat:
      count: "{{ duration + 1 }}"
      sequence:
        # Calculate current brightness and kelvin for this iteration (starting from 0)
        - variables:
            current_minute: "{{ repeat.index - 1 }}"
            target_brightness: "{{ [[(brightness_increment * current_minute) | int, 1] | max, max_brightness_value] | min }}"
            target_brightness_pct: "{{ (target_brightness * 100 / 255) | int }}"
            target_kelvin: "{{ [(start_kelvin + (kelvin_increment * current_minute)) | int, stop_kelvin] | min }}"

        # Set the light to the calculated values with a 60-second transition
        - service: light.turn_on
          target: !input target_lights
          data:
            brightness: "{{ target_brightness | int }}"
            color_temp_kelvin: "{{ target_kelvin | int }}"
            transition: 60

        # Log current settings to Activity log
        - service: logbook.log
          data:
            name: "Sunrise Simulator"
            message: "Minute {{ current_minute }} of {{ duration }}: Brightness {{ target_brightness_pct }}% ({{ target_brightness }}/255), Kelvin {{ target_kelvin }}K"

        # Wait 1 minute before the next iteration (unless this is the last iteration)
        - if:
            - condition: template
              value_template: "{{ current_minute < duration }}"
          then:
            - delay:
                minutes: 1

  # Run post-sunrise actions
  - choose: []
    default: !input post_sunrise_actions

  # Log completion to Home Assistant Activity log
  - service: logbook.log
    data:
      name: "Sunrise Simulator"
      message: "Sunrise simulation completed. Duration: {{ duration }} minutes, Final brightness: {{ max_brightness }}%, Final temperature: {{ stop_kelvin }}K"

mode: single
